Library.WebApp/Controllers/BookController.cs
using Library.WebApp.Models.Book;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Library.WebApp.Controllers
{
    public class BookController : Controller
    {
        public IConfiguration Configuration;

        public BookController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:hostUrl"];
            return Content(result);
        }

        private string GetControllerName()
        {
            string controllerName = ControllerContext.RouteData.Values["controller"].ToString();
            return controllerName;
        }


        public async Task<IActionResult> Index()
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            List<BookVM> booksList = new List<BookVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    booksList = JsonConvert.DeserializeObject<List<BookVM>>(apiResponse);
                }
            }

            return View(booksList);
        }

        [Authorize(Roles = "Librarian")]
        public IActionResult Create()
        {
            BookCreateVM book = new BookCreateVM();
            return View(book);
        }

        [Authorize(Roles = "Librarian")]
        [HttpPost]
        public async Task<IActionResult> Create(BookCreateVM book)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string bookJson = System.Text.Json.JsonSerializer.Serialize(book);
                    var content = new StringContent(bookJson, Encoding.UTF8, "application/json");

                    var response = await httpClient.PostAsync(_restpath, content);
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BookEditVM book = new BookEditVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<BookEditVM>(apiResponse);
                }
            }

            return View(book);
        }

        [HttpPost]
        [Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Edit(BookEditVM book)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BookEditVM result = new BookEditVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string bookJSON = System.Text.Json.JsonSerializer.Serialize(book);
                    var content = new StringContent(bookJSON, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{book.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<BookEditVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BookDetailsVM book = new BookDetailsVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/details/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<BookDetailsVM>(apiResponse);
                }
            }

            return View(book);
        }

        [Authorize(Roles = "Librarian")]
        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.DeleteAsync($"{_restpath}/{id}");
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Library.WebApp/Controllers/BorrowingController.cs
using Library.WebApp.Models.Borrowing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Library.WebApp.Controllers
{
    [Authorize(Roles = "Librarian,Admin")]
    public class BorrowingController : Controller
    {
        public IConfiguration Configuration;

        public BorrowingController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:hostUrl"];
            return Content(result);
        }

        private string GetControllerName()
        {
            string controllerName = ControllerContext.RouteData.Values["controller"].ToString();
            return controllerName;
        }


        public async Task<IActionResult> Index()
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            List<BorrowingVM> borrowingList = new List<BorrowingVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    borrowingList = JsonConvert.DeserializeObject<List<BorrowingVM>>(apiResponse);
                }
            }

            return View(borrowingList);
        }

        public IActionResult Create()
        {
            BorrowingCreateVM borrowing = new BorrowingCreateVM();
            return View(borrowing);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BorrowingCreateVM borrowing)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string borrowingJson = System.Text.Json.JsonSerializer.Serialize(borrowing);
                    var content = new StringContent(borrowingJson, Encoding.UTF8, "application/json");

                    var response = await httpClient.PostAsync(_restpath, content);
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BorrowingEditVM borrowing = new BorrowingEditVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    borrowing = JsonConvert.DeserializeObject<BorrowingEditVM>(apiResponse);
                }
            }

            return View(borrowing);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BorrowingEditVM borrowing)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BorrowingEditVM result = new BorrowingEditVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string borrowingJSON = System.Text.Json.JsonSerializer.Serialize(borrowing);
                    var content = new StringContent(borrowingJSON, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{borrowing.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<BorrowingEditVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            BorrowingDetailsVM borrowing = new BorrowingDetailsVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/details/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    borrowing = JsonConvert.DeserializeObject<BorrowingDetailsVM>(apiResponse);
                }
            }

            return View(borrowing);
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.DeleteAsync($"{_restpath}/{id}");
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Library.WebApp/Controllers/ReaderController.cs
using Library.WebApp.Models.Reader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Library.WebApp.Controllers
{
    [Authorize(Roles = "Librarian,Admin")]
    public class ReaderController : Controller
    {
        public IConfiguration Configuration;

        public ReaderController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:hostUrl"];
            return Content(result);
        }

        private string GetControllerName()
        {
            string controllerName = ControllerContext.RouteData.Values["controller"].ToString();
            return controllerName;
        }


        public async Task<IActionResult> Index()
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            List<ReaderVM> readerList = new List<ReaderVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    readerList = JsonConvert.DeserializeObject<List<ReaderVM>>(apiResponse);
                }
            }

            return View(readerList);
        }

        public IActionResult Create()
        {
            ReaderCreateVM reader = new ReaderCreateVM();
            return View(reader);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReaderCreateVM reader)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string readerJson = System.Text.Json.JsonSerializer.Serialize(reader);
                    var content = new StringContent(readerJson, Encoding.UTF8, "application/json");

                    var response = await httpClient.PostAsync(_restpath, content);
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            ReaderEditVM reader = new ReaderEditVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reader = JsonConvert.DeserializeObject<ReaderEditVM>(apiResponse);
                }
            }

            return View(reader);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ReaderEditVM reader)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            ReaderEditVM result = new ReaderEditVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string readerJSON = System.Text.Json.JsonSerializer.Serialize(reader);
                    var content = new StringContent(readerJSON, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{reader.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<ReaderEditVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            ReaderDetailsVM reader = new ReaderDetailsVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/details/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reader = JsonConvert.DeserializeObject<ReaderDetailsVM>(apiResponse);
                }
            }

            return View(reader);
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + GetControllerName();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.DeleteAsync($"{_restpath}/{id}");
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Library.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Katalog</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BranchLibrary" asp-action="Index">Biblioteki</a>
                        </li>

                        @{
                            if (User.IsInRole("Admin") || User.IsInRole("Trainer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Borrowing" asp-action="Index">Wyporzyczenia</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reader" asp-action="Index">Czytelnicy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Librarian" asp-action="Index">Bibliotekarze</a>
                                </li>
                            }
                        }
                        
                            @* Rejestracja, Wylogowanie, Zalogowanie, Zalogowany user *@
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-link text-dark">
                                    Witaj @User.Identity.Name
                                </li>

                                <li class="nav-link text-dark">
                                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                        <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RegisterReader">Zarejestruj się</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj się</a>
                                </li>
                            }
          

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>